var express = require('express');
var adminController = require('../controllers/admin.controller.js');

var router = express.Router();
router.get('/', adminController.home);
router.get('/class', adminController.lop);
router.post('/class/edit', adminController.edit);
router.get('/class/:lop', adminController.lop_student);
router.post('/class/add', adminController.add_class);
router.get('/class/delete/:id', adminController.delete_class);
router.get('/account', adminController.account);
router.get('/delete/:table/:col/:id', adminController.delete);
router.get('/student', adminController.student);
router.post('/student/update', adminController.update_student);
router.post('/student/add', adminController.insert_student);
router.get('/teacher', adminController.teacher);
router.post('/teacher/add', adminController.insert_teacher);
router.post('/teacher/update', adminController.update_teacher);
router.get('/subject', adminController.subject);
router.post('/subject/add', adminController.insert_subject);
router.post('/subject/update', adminController.update_subject);
router.get('/calendar', adminController.calendar);
router.post('/calendar/add', adminController.calendar_add);
router.post('/calendar/edit', adminController.calendar_edit);
router.get('/select/:table/:col/:val', adminController.select_col);
router.get('/modules', adminController.lop_hoc_phan);
router.get('/modules/:lop', adminController.show_lop_hp);
router.get('/modules/addsv/:ma_mon_hoc', adminController.select_addSV);
router.post('/modules/addSV', adminController.insert_addSV);
router.post('/modules/editSV', adminController.editSV_lhp);
router.post('/modules/add', adminController.add_lop_hp);
router.post('/modules/update', adminController.update_lop_hp);
router.get('/:table', adminController.select);
module.exports = router;